# Site settings
title: Kyle Graycar
email: kgraycar@gmail.com
description: I'm a clean energy techie. Welcome to my site.
baseurl: ""
url: "http://kylegraycar.me"
safe: false
twitter_username: kylegraycar
github_username:  kylegraycar
timezone:       default
locale:         en_us
name:           "Kyle Graycar"
icon:           /favicons/mstile-310x310.png
author:
  facebook:     hellohellohellohellohellohellohellohello
  twitter:      
fb_admins:      713640720

# Build settings
markdown: kramdown
